apiVersion: v1
kind: ConfigMap
metadata:
    name: ctfd
    namespace: {{ .Release.Namespace }}
data:
  DOCKER_HOST: ssh://ctfd-worker

  WORKERS: "4"
  LMS_BASE_URL: https://lms.infosec.moscow/api
  REDIS_HOST: redis://redis:6379
  DATABASE_HOST: ctfd-mariadb-maxscale
  DATABASE_PROTOCOL: mysql+pymysql
  DATABASE_PORT: "3306"

  AWS_S3_BUCKET: ctfd-infosec-moscow
  AWS_S3_ENDPOINT_URL: https://storage.yandexcloud.net
  AWS_S3_REGION: ru-central1

  UPLOAD_PROVIDER: s3
  LOG_FOLDER: /var/log/CTFd
  ACCESS_LOG: /var/log/CTFd/access.log
  ERROR_LOG: /var/log/CTFd/error.log

  PROBLEM_DOCKER_RUN_FOLDER: /home/docker
  REVERSE_PROXY: "true"
