apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctfd
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.ctfd.replicas }}
  selector:
    matchLabels:
      app: ctfd
  template:
    metadata:
      labels:
        app: ctfd
    spec:
      nodeName: cl1nsn5jic32dpnlnmsf-ovur
      initContainers:
        - name: copy-ssh
          image: alpine:3.22.1
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk update
              apk add openssh-client
              cp -aL /ssh-secret/* /ssh/ && \
              chmod 600 /ssh/*.key || true && \
              chmod 700 /ssh && \
              ssh-keyscan worker.ctfd.infosec.moscow >> /ssh/.known_hosts && \
              chown -R 1001:1001 /ssh

          volumeMounts:
            - name: ssh-secret
              mountPath: /ssh-secret
              readOnly: true
            - name: ssh
              mountPath: /ssh

      containers:
        - name: ctfd
          image: cr.yandex/crpi7be6fcnum9d5jo38/ctfd:v10
          envFrom:
            - configMapRef:
                name: ctfd
            - secretRef:
                name: ctfd
            - secretRef:
                name: ctfd-mariadb
          volumeMounts:
            - name: ssh
              mountPath: /home/ctfd/.ssh
            - name: ctfd-tasks
              mountPath: /opt/CTFd/CTFd/plugins/ctfd-owl/source/tasks
            - name: user-task-folders
              mountPath: /home/docker

      volumes:
        - name: ssh-secret
          secret:
            secretName: ctfd-docker-worker
        - name: ssh
          emptyDir: {}
        - name: ctfd-tasks
          hostPath:
            path: /mnt/ctfd-tasks
            type: Directory
        - name: user-task-folders
          hostPath:
            path: /mnt/user-dirs
            type: Directory
