apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctfd
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.ctfd.replicas }}
  selector:
    matchLabels:
      app: ctfd
  template:
    metadata:
      labels:
        app: ctfd
    spec:
      initContainers:
        - name: copy-ssh
          image: busybox:1.36
          command: ["/bin/sh", "-c"]
          args:
            - |
              cp -aL /ssh-secret/* /ssh/ && \
              chmod 600 /ssh/*.key || true && \
              chmod 644 /ssh/*.pub || true && \
              chmod 700 /ssh && \
              ssh-keyscan -F /ssh/config ctfd-worker >> /ssh/.known_hosts && \
              chown -R 1001:1001 /ssh

          volumeMounts:
            - name: ssh-secret
              mountPath: /ssh-secret
              readOnly: true
            - name: ssh
              mountPath: /ssh

      containers:
        - name: ctfd
          image: cr.yandex/crpi7be6fcnum9d5jo38/ctfd:v6
          envFrom:
            - configMapRef:
                name: ctfd
            - secretRef:
                name: ctfd
            - secretRef:
                name: ctfd-mariadb
          volumeMounts:
            - name: ssh
              mountPath: /home/ctfd/.ssh

      volumes:
        - name: ssh-secret
          secret:
            secretName: ctfd-docker-worker
        - name: ssh
          emptyDir: {}

