services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lms
    ports:
      - 5432:5432

  redis:
    image: redis:8.0.0-alpine3.21
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  s3:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=miniouser
      - MINIO_ROOT_PASSWORD=miniopassword
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
  # backend:
  #   image: lms-backend:latest
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./iam-key.json:/iam-key.json
  #   depends_on:
  #     - db
  #     - redis
  #     - s3