services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lms
    ports:
      - 5432:5432

  redis:
    image: redis:8.0.0-alpine3.21
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: cr.yandex/crpi7be6fcnum9d5jo38/lms-backend:0.0.10
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./iam-key.json:/iam-key.json
    depends_on:
      - db
      - redis
      - s3
