image:
  backend_img: ghcr.io/mscw-infosec/lms
  backend_tag: 0.0.7
  frontend_img: ghcr.io/mscw-infosec/lms-frontend
  frontend_tag: 0.0.1
  pullPolicy: IfNotPresent

BACKEND_PORT: 8080
FRONTEND_PORT: 3000

secrets: {}
