apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: yandex-cr-auth
  namespace: cert-manager
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: yandex-lockbox

  target:
    name: yandex-cr-auth
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson

  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: e6qqm8her3thune5v1vp
        property: .dockerconfigjson
