apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: backup
spec:
  mariaDbRef:
    name: ctfd-mariadb
  schedule:
    cron: "0 0 * * *"
    suspend: false
  maxRetention: 72h # 3 * 24
  compression: gzip
  storage:
    s3:
      bucket: ctfd-mariadb-backups
      prefix: mariadb
      endpoint: storage.yandexcloud.net
      region:  ru-central1
      accessKeyIdSecretKeyRef:
        name: ctfd-mariadb-backups
        key: access-key-id
      secretAccessKeySecretKeyRef:
        name: ctfd-mariadb-backups
        key: secret-access-key

