apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: ctfd
  namespace: {{ .Release.Namespace }}
spec:
  mariaDbRef:
    name: ctfd-mariadb
  characterSet: utf8mb4
  collate: utf8mb4_unicode_ci
