apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 77.0.2
      helm:
        releaseName: kube-prometheus-stack
        valuesObject:
          prometheus:
            prometheusSpec:
              additionalScrapeConfigs:
                - job_name: "external-node-exporter"
                  static_configs:
                    - targets: ["94.126.204.151:9100"]
                      labels:
                        cluster: "external-nodes"
                  scheme: http
                  metrics_path: /metrics
                  scrape_interval: 30s
                  scrape_timeout: 10s

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
