apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lms
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:mscw-infosec/lms.git'
    targetRevision: HEAD
    path: k8s
    helm:
      valueFiles:
        - values.yaml
        - values-pre.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: lms
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
