apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://ot-container-kit.github.io/helm-charts/
    targetRevision: "0.21.2"
    chart: redis-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: redis-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
