apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: monitoring
stringData:
  prometheus-additional.yaml: |
    - job_name: 'ctfd-worker-node-exporter'
      static_configs:
        - targets: ['94.126.204.151:9100']
