apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: iam-key
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    iam-key.json:  {{ .Values.secrets.IAM_KEY }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: iam-key
      namespace: {{ .Release.Namespace }}
