apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
spec:
  instances: 2
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: lms
      owner: lms
      secret:
        name: lms-pg-secrets
