apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: lms-pg-secrets
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    username: {{ .Values.secrets.POSTGRES_PASSWORD }}
    password: {{ .Values.secrets.POSTGRES_USER }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: lms-pg-secrets
      namespace: {{ .Release.Namespace }}
