name: Deploy landing

on:
  push:
    branches:
      - main
    paths:
      - "landing/**"

jobs:
  deploy:
    runs-on: blacksmith-8vcpu-ubuntu-2404
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}-landing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set image version
        run: echo "IMAGE_VERSION=0.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: landing
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}-cache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}-cache,mode=max
